version: '3'

services:
  fastapi-app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    restart: always

  mongo:
    container_name: my-mongodb-container
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
